vae:
  # num channels in input and output
  in_channels: 3
  out_channels: 3
  # base number of channels in the encoder and decoder.
  channels: 128
  # how the channels change in the encoder and decoder.
  channels_mult: [1, 2, 4, 4]
  # number of residual blocks in the upsampling (dec.) and downsampling (enc.) path.
  num_res_blocks: 2
  # resolution at which to apply self-attention in the encoder downsampling.
  attn_resolutions: [32]
  dropout: 0.0
  # input resolution
  resolution: 256
  # latent size, for VAE the encoder predicts 2 * latent_size.
  # representing the mean and logvar of the latent distribution.
  z_channels: 4
  # spatial compression controls how much to 
  spatial_compression: 8
  # wavelet settings
  wavelet: null # supports the wavelets from PyWavelets
  maxlevel: 1 # number of levels to apply wavelet transform

